name: Golangci Lint

on:
  push:
    branches: [master]
  pull_request:
env:
  GOPROXY: "https://proxy.golang.org"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init Go modules
        run: go mod init github.com/guanguans/id-validator
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
